sudo: required
dist: trusty
language: python
python:
    - 3.4
before_install:
    - sh scripts/setup.sh;
addons:
    postgresql: "9.4"
before_script:
    - psql -c 'create database mprorp;' -U postgres
    - pip3 install sqlalchemy
script:
    - nosetests3 mprorp/tests/*
notifications:
    slack: ovdinfo:pC2a1JMfPsjs3hKPAzz7yPUB

