sudo: required
dist: trusty
language: python
python:
    - 3.4
before_install:
    - sh scripts/setup.sh;
    - sh scripts/tomita.sh ~;
addons:
    postgresql: "9.4"
before_script:
    - psql -c 'create database mprorp;' -U postgres
    - psql -c 'CREATE EXTENSION "uuid-ossp";' -U postgres -d mprorp
script:
    - cd local_entrypoints
    - python3 times.py
    - sudo nosetests3 mprorp/tests/*
notifications:
    slack: ovdinfo:pC2a1JMfPsjs3hKPAzz7yPUB

