#!/bin/sh -e
# ============================================
#  flowerd - Starts the Celery flower daemon.
# ============================================
#
# :Usage: /etc/init.d/flowerd {start}
# :Configuration file: /etc/default/celeryd


### BEGIN INIT INFO
# Provides:          flowerd
# Required-Start:    $network $local_fs $remote_fs
# Required-Stop:     $network $local_fs $remote_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: celery flower daemon
### END INIT INFO

# some commands work asyncronously, so we'll wait this many seconds
SLEEP_SECONDS=5

FLOWERD_DEFAULTS=${FLOWERD_DEFAULTS:-"/etc/default/flowerd"}

test -f "$FLOWERD_DEFAULTS" && . "$FLOWERD_DEFAULTS"

# Extra start-stop-daemon options, like user/group.
if [ -n "$FLOWERD_USER" ]; then
    DAEMON_OPTS="$DAEMON_OPTS --uid=$FLOWERD_USER"
fi
if [ -n "$FLOWERD_GROUP" ]; then
    DAEMON_OPTS="$DAEMON_OPTS --gid=$FLOWERD_GROUP"
fi

if [ -n "$FLOWERD_CHDIR" ]; then
    DAEMON_OPTS="$DAEMON_OPTS --workdir=$FLOWERD_CHDIR"
fi



export PATH="${PATH:+$PATH:}/usr/sbin:/sbin"

start_script () {
    $FLOWERD_BIN $DAEMON_OPTS
    sleep $SLEEP_SECONDS
}


case "$1" in
    start)
        start_script
    ;;

    *)
        echo "Usage: /etc/init.d/flowerd {start}"
        exit 64  # EX_USAGE
    ;;
esac

exit 0
